/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ticktoe.java
 *
 * Created on Sep 28, 2012, 3:39:04 PM
 */
package tick.tak.toe;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Anish Ratnawat
 */
public class ticktoe extends javax.swing.JFrame {
int turn=0;
int bc00=0;
int bc01=0;
int bc02=0;
int bc10=0;
int bc11=0;
int bc12=0;
int bc20=0;
int bc21=0;
int bc22=0;
int enter=0;
int playc=0;
int dc=0;
int check=0;
String player1=null,player2=null;
int p1wins=0,p2wins=0;
         Image myImage=null,myImage1=null;        
Icon imgic=new ImageIcon("oscilloscope.png");
    /** Creates new form ticktoe */
    public ticktoe() {
        initComponents();
        getContentPane().setBackground(Color.white);
        this.setTitle("JticToe-play unlimited");
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(ticktoe.class.getResource("jticktoe.gif")));
       inita();

    }
public final void inita()
{
    b00.setText(" ");
 b01.setText(" ");
 b02.setText(" ");
 b10.setText(" ");
 b11.setText(" ");
 b12.setText(" ");
 b20.setText(" ");
 b21.setText(" ");
 b22.setText(" ");
 try {
            myImage = ImageIO.read(getClass().getResource("zero.jpg"));
            myImage1 = ImageIO.read(getClass().getResource("cross.jpg"));
        } catch (IOException ex) {
            Logger.getLogger(ticktoe.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p1score = new javax.swing.JLabel();
        p2score = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        pvc = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dvc = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        b12 = new javax.swing.JLabel();
        b11 = new javax.swing.JLabel();
        b00 = new javax.swing.JLabel();
        b01 = new javax.swing.JLabel();
        b02 = new javax.swing.JLabel();
        b10 = new javax.swing.JLabel();
        b20 = new javax.swing.JLabel();
        b21 = new javax.swing.JLabel();
        b22 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tick/tak/toe/newgame.jpg"))); // NOI18N
        jButton1.setToolTipText("New game with new player");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);
        jToolBar1.add(jSeparator1);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tick/tak/toe/playmore.jpg"))); // NOI18N
        jButton2.setToolTipText("play more with same player");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);
        jToolBar1.add(jSeparator2);
        jToolBar1.add(jLabel2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Player");

        jLabel3.setText("Name");

        jLabel4.setText("Score");

        jLabel5.setText("1");

        jLabel6.setText("2");

        p1.setText("player1");

        p2.setText("player2");

        p1score.setText("0");

        p2score.setText("0");

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel8.setText("Played count:");

        pvc.setText("0");

        jLabel10.setText("Draw games:");

        dvc.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(p1score))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(p2score))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pvc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dvc, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(p1)
                    .addComponent(p1score))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(p2)
                    .addComponent(p2score))
                .addContainerGap())
            .addComponent(jSeparator7, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(pvc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(dvc))
                .addGap(26, 26, 26))
        );

        jToolBar1.add(jPanel1);

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        b12.setBackground(new java.awt.Color(255, 255, 255));
        b12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b12MouseClicked(evt);
            }
        });

        b11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b11MouseClicked(evt);
            }
        });

        b00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b00MouseClicked(evt);
            }
        });

        b01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b01MouseClicked(evt);
            }
        });

        b02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b02MouseClicked(evt);
            }
        });

        b10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b10MouseClicked(evt);
            }
        });

        b20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b20MouseClicked(evt);
            }
        });

        b21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b21MouseClicked(evt);
            }
        });

        b22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b22MouseClicked(evt);
            }
        });

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tick/tak/toe/j.jpg"))); // NOI18N

        jMenu1.setText("File");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Option");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("New Game");
        jMenuItem2.setToolTipText("New game with new player");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Play more");
        jMenuItem3.setToolTipText("Play more with same player\n");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("About");

        jMenuItem4.setText("About");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(b00, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b20, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b21, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b01, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b02, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b22, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
            .addComponent(jSeparator8, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(180, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b00, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b01, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b02, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b20, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b21, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b22, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(365, 365, 365)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(146, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       if(enter==1)
       {int a=JOptionPane.showConfirmDialog(this,"Wanna play new game(old game score lost)","New game",0);
           if(a==0){excecute();}
           else{
       }
       }
       else{excecute();}
       
      
    }//GEN-LAST:event_jButton1ActionPerformed
 void excecute(){
        enter=0;
         if(enter==0)
        {  player1=JOptionPane.showInputDialog(this, "player1 name(0)", rootPaneCheckingEnabled);
        player2=JOptionPane.showInputDialog(this, "player2 name(1)", rootPaneCheckingEnabled);
       // System.out.print(player1);
       
        p1.setText(player1);
        p2.setText(player2);
        enter++;
       jButton2ActionPerformed(null);
        p1wins=0;
        p2wins=0;
        playc=0;
        dc=0;
        pvc.setText("0");
        dvc.setText("0");
        p1score.setText("0");
        p2score.setText("0");
         check=0;
        }}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    if(enter==0){JOptionPane.showMessageDialog(this,"Click new game to play");
    }else{   if(dc==1){   
      }
      else{
    
 playc++;
 pvc.setText(Integer.toString(playc));
 check++;
      dvc.setText(Integer.toString(check));
      }
       dc=0;
        turn=0;
 bc00=0;
 bc01=0;
 bc02=0;
 bc10=0;
 bc11=0;
 bc12=0;
bc20=0;
 bc21=0;
 bc22=0;
 b00.setText(" ");b00.setIcon(null);
 b01.setText(" ");b01.setIcon(null);
 b02.setText(" ");b02.setIcon(null);
 b10.setText(" ");b10.setIcon(null);
 b11.setText(" ");b11.setIcon(null);
 b12.setText(" ");b12.setIcon(null);
 b20.setText(" ");b20.setIcon(null);
 b21.setText(" ");b21.setIcon(null);
 b22.setText(" ");b22.setIcon(null);
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void b12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b12MouseClicked
        // TODO add your handling code here:
             if(bc12==0){
                       if(enter==0)
               {
                    player1=JOptionPane.showInputDialog(this, "player1 name(0)", rootPaneCheckingEnabled);
        player2=JOptionPane.showInputDialog(this, "player2 name(1)", rootPaneCheckingEnabled);
        p1.setText(player1);
        p2.setText(player2); 
               enter++;
               }
        if(turn%2==0){
        b12.setText("0");
        b12.setIcon(new ImageIcon(myImage));
        }
        else{b12.setText("1");
        b12.setIcon(new ImageIcon(myImage1));}
        out:{
        if(b12.getText().equals(b02.getText())&&b12.getText().equals(b22.getText()))
        {
            if(turn%2==0){
            JOptionPane.showMessageDialog(this,"Player1:"+player1+" Won", "Result", 1);
            p1score.setText(Integer.toString(++p1wins));
            }
            else{
            JOptionPane.showMessageDialog(this,"Player2:"+player2+" Won", "Result", 1);
             p2score.setText(Integer.toString(++p2wins));}
            pvc.setText(Integer.toString(++playc));
            dc=1;
           jButton2ActionPerformed(null);
          // GOTO exitw;
          break out;
          
        }
                if(b12.getText().equals(b10.getText())&&b12.getText().equals(b11.getText())){
              if(turn%2==0){
            JOptionPane.showMessageDialog(this,"Player1:"+player1+" Won", "Result", 1);
              p1score.setText(Integer.toString(++p1wins));}
            else{
            JOptionPane.showMessageDialog(this,"Player2:"+player2+" Won", "Result", 1);
               p2score.setText(Integer.toString(++p2wins));}
              pvc.setText(Integer.toString(++playc));
              dc=1;
              jButton2ActionPerformed(null);
            //  GOTO exitw;
              break out;
                }
                
if(b00.getText()!=" "&&b01.getText()!=" "&&b02.getText()!=" "&&b10.getText()!=" "&&b11.getText()!=" "&&b12.getText()!=" "&&b20.getText()!=" "&&b21.getText()!=" "&&b22.getText()!=" "){
JOptionPane.showMessageDialog(this,"Game Draw.NObody win", "Result", 1);
jButton2ActionPerformed(null);
break out;
}
                     
       // System.out.print("inside");
        turn++;
        
             
        bc12=1;}}
       // exitw:System.out.println("anish");
    }//GEN-LAST:event_b12MouseClicked

    private void b11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b11MouseClicked
        // TODO add your handling code here:
         if(bc11==0){
               if(enter==0)
               {
                    player1=JOptionPane.showInputDialog(this, "player1 name(0)", rootPaneCheckingEnabled);
        player2=JOptionPane.showInputDialog(this, "player2 name(1)", rootPaneCheckingEnabled);
        p1.setText(player1);
        p2.setText(player2); 
               enter++;
               }
        if(turn%2==0){
        b11.setText("0");
        b11.setIcon(new ImageIcon(myImage));
        }
        else{b11.setText("1");
        b11.setIcon(new ImageIcon(myImage1));}
        out:{
        if(b11.getText().equals(b00.getText())&&b11.getText().equals(b22.getText()))
        {
           if(turn%2==0){
            JOptionPane.showMessageDialog(this,"Player1:"+player1+" Won", "Result", 1);
           p1score.setText(Integer.toString(++p1wins));}
            else{
            JOptionPane.showMessageDialog(this,"Player2:"+player2+" Won", "Result", 1);
            p2score.setText(Integer.toString(++p2wins));}
           pvc.setText(Integer.toString(++playc));
dc=1;           jButton2ActionPerformed(null);
break out;
        }
         if(b11.getText().equals(b20.getText())&&b11.getText().equals(b02.getText()))
        {
           if(turn%2==0){
            JOptionPane.showMessageDialog(this,"Player1:"+player1+" Won", "Result", 1);
           p1score.setText(Integer.toString(++p1wins));}
            else{
            JOptionPane.showMessageDialog(this,"Player2:"+player2+" Won", "Result", 1);
            p2score.setText(Integer.toString(++p2wins));}
           pvc.setText(Integer.toString(++playc));
dc=1;           jButton2ActionPerformed(null);
break out;
        }
                if(b11.getText().equals(b10.getText())&&b11.getText().equals(b12.getText())){
                if(turn%2==0){
            JOptionPane.showMessageDialog(this,"Player1:"+player1+" Won", "Result", 1);
                p1score.setText(Integer.toString(++p1wins));}
            else{
            JOptionPane.showMessageDialog(this,"Player2:"+player2+" Won", "Result", 1);
                 p2score.setText(Integer.toString(++p2wins));}
                pvc.setText(Integer.toString(++playc));
                dc=1;
                jButton2ActionPerformed(null);
                break out;
                }
               if(b11.getText().equals(b01.getText())&&b11.getText().equals(b21.getText())){
                if(turn%2==0){
            JOptionPane.showMessageDialog(this,"Player1:"+player1+" Won", "Result", 1);
                p1score.setText(Integer.toString(++p1wins));}
            else{
            JOptionPane.showMessageDialog(this,"Player2:"+player2+" Won", "Result", 1);
                 p2score.setText(Integer.toString(++p2wins));}
                pvc.setText(Integer.toString(++playc));
                dc=1;
               jButton2ActionPerformed(null);
               break out;
                }         
        if(b00.getText()!=" "&&b01.getText()!=" "&&b02.getText()!=" "&&b10.getText()!=" "&&b11.getText()!=" "&&b12.getText()!=" "&&b20.getText()!=" "&&b21.getText()!=" "&&b22.getText()!=" "){
JOptionPane.showMessageDialog(this,"Game Draw.NObody win", "Result", 1);
jButton2ActionPerformed(null);
break out;
}
        if(b00.getText()!=" "&&b01.getText()!=" "&&b02.getText()!=" "&&b10.getText()!=" "&&b11.getText()!=" "&&b12.getText()!=" "&&b20.getText()!=" "&&b21.getText()!=" "&&b22.getText()!=" "){
JOptionPane.showMessageDialog(this,"Game Draw.NObody win", "Result", 1);
jButton2ActionPerformed(null);
break out;
}
        turn++;
        
        bc11=1;}}
    }//GEN-LAST:event_b11MouseClicked

    private void b00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b00MouseClicked
        // TODO add your handling code here:
        if(bc00==0){
              if(enter==0)
               {
                    player1=JOptionPane.showInputDialog(this, "player1 name(0)", rootPaneCheckingEnabled);
        player2=JOptionPane.showInputDialog(this, "player2 name(1)", rootPaneCheckingEnabled);
        p1.setText(player1);
        p2.setText(player2); 
               enter++;
               }
        if(turn%2==0){
        b00.setText("0");
        b00.setIcon(new ImageIcon(myImage));
        }
        else{b00.setText("1");
        b00.setIcon(new ImageIcon(myImage1));}
        out:{
        if(b00.getText().equals(b11.getText())&&b00.getText().equals(b22.getText()))
        {
           if(turn%2==0){
            JOptionPane.showMessageDialog(this,"Player1:"+player1+" Won", "Result", 1);
           p1score.setText(Integer.toString(++p1wins));}
            else{
            JOptionPane.showMessageDialog(this,"Player2:"+player2+" Won", "Result", 1);
            p2score.setText(Integer.toString(++p2wins));}
           pvc.setText(Integer.toString(++playc));
           dc=1;
           jButton2ActionPerformed(null);
           break out;
        }
                if(b00.getText().equals(b01.getText())&&b00.getText().equals(b02.getText())){
               if(turn%2==0){
            JOptionPane.showMessageDialog(this,"Player1:"+player1+" Won", "Result", 1);
               p1score.setText(Integer.toString(++p1wins));}
            else{
            JOptionPane.showMessageDialog(this,"Player2:"+player2+" Won", "Result", 1);
                p2score.setText(Integer.toString(++p2wins));}
               pvc.setText(Integer.toString(++playc));
               dc=1;
              jButton2ActionPerformed(null);
              break out;
                }
               if(b00.getText().equals(b10.getText())&&b00.getText().equals(b20.getText())){
                if(turn%2==0){
            JOptionPane.showMessageDialog(this,"Player1:"+player1+" Won", "Result", 1);
                p1score.setText(Integer.toString(++p1wins));}
            else{
            JOptionPane.showMessageDialog(this,"Player2:"+player2+" Won", "Result", 1);
                 p2score.setText(Integer.toString(++p2wins));}
                pvc.setText(Integer.toString(++playc));
                dc=1;
               jButton2ActionPerformed(null);
               break out;
                }         
        if(b00.getText()!=" "&&b01.getText()!=" "&&b02.getText()!=" "&&b10.getText()!=" "&&b11.getText()!=" "&&b12.getText()!=" "&&b20.getText()!=" "&&b21.getText()!=" "&&b22.getText()!=" "){
JOptionPane.showMessageDialog(this,"Game Draw.NObody win", "Result", 1);
jButton2ActionPerformed(null);
break out;
}
        turn++;
        
        bc00=1;
        }}
    }//GEN-LAST:event_b00MouseClicked

    private void b01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b01MouseClicked
        // TODO add your handling code here:
         if(bc01==0){
               if(enter==0)
               {
                    player1=JOptionPane.showInputDialog(this, "player1 name(0)", rootPaneCheckingEnabled);
        player2=JOptionPane.showInputDialog(this, "player2 name(1)", rootPaneCheckingEnabled);
        p1.setText(player1);
        p2.setText(player2); 
               enter++;
               }
        if(turn%2==0){
            b01.setText("0");
       b01.setIcon(new ImageIcon(myImage));
        }
        else{b01.setText("1");
        b01.setIcon(new ImageIcon(myImage1));}
        out:{
        if(b01.getText().equals(b00.getText())&&b01.getText().equals(b02.getText()))
        {
            if(turn%2==0){
            JOptionPane.showMessageDialog(this,"Player1:"+player1+" Won", "Result", 1);
            p1score.setText(Integer.toString(++p1wins));
            }
            else{
            JOptionPane.showMessageDialog(this,"Player2:"+player2+" Won", "Result", 1);
             p2score.setText(Integer.toString(++p2wins));}
            pvc.setText(Integer.toString(++playc));
            dc=1;
            jButton2ActionPerformed(null);
            break out;
            }
        
                if(b01.getText().equals(b11.getText())&&b01.getText().equals(b21.getText())){
                if(turn%2==0){
            JOptionPane.showMessageDialog(this,"Player1:"+player1+" Won", "Result", 1);}
            else{
            JOptionPane.showMessageDialog(this,"Player2:"+player2+" Won", "Result", 1);
                 p2score.setText(Integer.toString(++p2wins));}
                pvc.setText(Integer.toString(++playc));
               dc=1;
               jButton2ActionPerformed(null);
               break out;
                }
                if(b00.getText()!=" "&&b01.getText()!=" "&&b02.getText()!=" "&&b10.getText()!=" "&&b11.getText()!=" "&&b12.getText()!=" "&&b20.getText()!=" "&&b21.getText()!=" "&&b22.getText()!=" "){
JOptionPane.showMessageDialog(this,"Game Draw.NObody win", "Result", 1);
jButton2ActionPerformed(null);
break out;
}     
        
        turn++;
        
        bc01=1;
         }}
    }//GEN-LAST:event_b01MouseClicked

    private void b02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b02MouseClicked
        // TODO add your handling code here:
        
    if(bc02==0){
                    if(enter==0)
               {
                    player1=JOptionPane.showInputDialog(this, "player1 name(0)", rootPaneCheckingEnabled);
        player2=JOptionPane.showInputDialog(this, "player2 name(1)", rootPaneCheckingEnabled);
        p1.setText(player1);
        p2.setText(player2); 
               enter++;
               }
        if(turn%2==0){
        b02.setText("0");
        b02.setIcon(new ImageIcon(myImage));
        }
        else{b02.setText("1");
        b02.setIcon(new ImageIcon(myImage1));}
        out:{
        if(b02.getText().equals(b00.getText())&&b02.getText().equals(b01.getText()))
        {
            if(turn%2==0){
            JOptionPane.showMessageDialog(this,"Player1:"+player1+" Won", "Result", 1);
            p1score.setText(Integer.toString(++p1wins));}
            else{
            JOptionPane.showMessageDialog(this,"Player2:"+player2+" Won", "Result", 1);
            p2score.setText(Integer.toString(++p2wins));}
            pvc.setText(Integer.toString(++playc));
            dc=1;
            jButton2ActionPerformed(null);
            break out;
        }
                if(b02.getText().equals(b12.getText())&&b02.getText().equals(b22.getText())){
                if(turn%2==0){
            JOptionPane.showMessageDialog(this,"Player1:"+player1+" Won", "Result", 1);
                p1score.setText(Integer.toString(++p1wins));}
            else{
            JOptionPane.showMessageDialog(this,"Player2:"+player2+" Won", "Result", 1);
                p2score.setText(Integer.toString(++p2wins));}
                pvc.setText(Integer.toString(++playc));
                dc=1;
               jButton2ActionPerformed(null);
               break out;
                }
                 if(b02.getText().equals(b11.getText())&&b02.getText().equals(b20.getText())){
                if(turn%2==0){
            JOptionPane.showMessageDialog(this,"Player1:"+player1+" Won", "Result", 1);
                p1score.setText(Integer.toString(++p1wins));}
            else{
            JOptionPane.showMessageDialog(this,"Player2:"+player2+" Won", "Result", 1);
                p2score.setText(Integer.toString(++p2wins));}
                pvc.setText(Integer.toString(++playc));
                dc=1;
                jButton2ActionPerformed(null);
                break out;
                }
                if(b00.getText()!=" "&&b01.getText()!=" "&&b02.getText()!=" "&&b10.getText()!=" "&&b11.getText()!=" "&&b12.getText()!=" "&&b20.getText()!=" "&&b21.getText()!=" "&&b22.getText()!=" "){
JOptionPane.showMessageDialog(this,"Game Draw.NObody win", "Result", 1);
jButton2ActionPerformed(null);
break out;
}
                     
        
        turn++;
        
        bc02=1;
        }
    }
        
    }//GEN-LAST:event_b02MouseClicked

    private void b10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b10MouseClicked
        // TODO add your handling code here:
           if(bc10==0){
                      if(enter==0)
               {
                    player1=JOptionPane.showInputDialog(this, "player1 name(0)", rootPaneCheckingEnabled);
        player2=JOptionPane.showInputDialog(this, "player2 name(1)", rootPaneCheckingEnabled);
        p1.setText(player1);
        p2.setText(player2); 
               enter++;
               }
        if(turn%2==0){
        b10.setText("0");
        b10.setIcon(new ImageIcon(myImage));
        }
        else{b10.setText("1");
        b10.setIcon(new ImageIcon(myImage1));}
        out:{
        if(b10.getText().equals(b00.getText())&&b10.getText().equals(b20.getText()))
        {
           if(turn%2==0){
            JOptionPane.showMessageDialog(this,"Player1:"+player1+" Won", "Result", 1);
           p1score.setText(Integer.toString(++p1wins));}
            else{
            JOptionPane.showMessageDialog(this,"Player2:"+player2+" Won", "Result", 1);
           p2score.setText(Integer.toString(++p2wins));}
           pvc.setText(Integer.toString(++playc));
                dc=1;
           jButton2ActionPerformed(null);
           break out;
        }
                if(b10.getText().equals(b11.getText())&&b10.getText().equals(b12.getText())){
                if(turn%2==0){
            JOptionPane.showMessageDialog(this,"Player1:"+player1+" Won", "Result", 1);
                p1score.setText(Integer.toString(++p1wins));}
            else{
            JOptionPane.showMessageDialog(this,"Player2:"+player2+" Won", "Result", 1);
                p2score.setText(Integer.toString(++p2wins));}
                pvc.setText(Integer.toString(++playc));
                dc=1;
              jButton2ActionPerformed(null);
              break out;
                }
                 if(b00.getText()!=" "&&b01.getText()!=" "&&b02.getText()!=" "&&b10.getText()!=" "&&b11.getText()!=" "&&b12.getText()!=" "&&b20.getText()!=" "&&b21.getText()!=" "&&b22.getText()!=" "){
JOptionPane.showMessageDialog(this,"Game Draw.NObody win", "Result", 1);
jButton2ActionPerformed(null);
break out;
}    
        
        turn++;
        
        bc10=1;}}
    }//GEN-LAST:event_b10MouseClicked

    private void b20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b20MouseClicked
        // TODO add your handling code here:
            if(bc20==0){
                       if(enter==0)
               {
                    player1=JOptionPane.showInputDialog(this, "player1 name(0)", rootPaneCheckingEnabled);
        player2=JOptionPane.showInputDialog(this, "player2 name(1)", rootPaneCheckingEnabled);
        p1.setText(player1);
        p2.setText(player2); 
               enter++;
               }
        if(turn%2==0){
        b20.setText("0");
        b20.setIcon(new ImageIcon(myImage));
        }
        else{b20.setText("1");
        b20.setIcon(new ImageIcon(myImage1));}
       out:{
        if(b20.getText().equals(b21.getText())&&b20.getText().equals(b22.getText()))
        {
         if(turn%2==0){
            JOptionPane.showMessageDialog(this,"Player1:"+player1+" Won", "Result", 1);
         p1score.setText(Integer.toString(++p1wins));}
            else{
            JOptionPane.showMessageDialog(this,"Player2:"+player2+" Won", "Result", 1);
         p2score.setText(Integer.toString(++p2wins));}
         pvc.setText(Integer.toString(++playc));
                dc=1;
        jButton2ActionPerformed(null);
        break out;
        }
        
                if(b20.getText().equals(b00.getText())&&b20.getText().equals(b10.getText())){
                if(turn%2==0){
            JOptionPane.showMessageDialog(this,"Player1:"+player1+" Won", "Result", 1);
                p1score.setText(Integer.toString(++p1wins));}
            else{
            JOptionPane.showMessageDialog(this,"Player2:"+player2+" Won", "Result", 1);
                p2score.setText(Integer.toString(++p2wins));}
                pvc.setText(Integer.toString(++playc));
                dc=1;
               jButton2ActionPerformed(null);
               break out;
                }
                  if(b20.getText().equals(b11.getText())&&b20.getText().equals(b02.getText())){
                if(turn%2==0){
            JOptionPane.showMessageDialog(this,"Player1:"+player1+" Won", "Result", 1);
                p1score.setText(Integer.toString(++p1wins));}
            else{
            JOptionPane.showMessageDialog(this,"Player2:"+player2+" Won", "Result", 1);
                p2score.setText(Integer.toString(++p2wins));}
                pvc.setText(Integer.toString(++playc));
                dc=1;
               jButton2ActionPerformed(null);
               break out;
                }
                if(b00.getText()!=" "&&b01.getText()!=" "&&b02.getText()!=" "&&b10.getText()!=" "&&b11.getText()!=" "&&b12.getText()!=" "&&b20.getText()!=" "&&b21.getText()!=" "&&b22.getText()!=" "){
JOptionPane.showMessageDialog(this,"Game Draw.NObody win", "Result", 1);
jButton2ActionPerformed(null);
break out;
}
                     
        
        turn++;
        
        bc20=1;}}
    }//GEN-LAST:event_b20MouseClicked

    private void b21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b21MouseClicked
        // TODO add your handling code here:
              if(bc21==0){
                       if(enter==0)
               {
                    player1=JOptionPane.showInputDialog(this, "player1 name(0)", rootPaneCheckingEnabled);
        player2=JOptionPane.showInputDialog(this, "player2 name(1)", rootPaneCheckingEnabled);
        p1.setText(player1);
        p2.setText(player2); 
               enter++;
               }
        if(turn%2==0){
        b21.setText("0");
        b21.setIcon(new ImageIcon(myImage));
        }
        else{b21.setText("1");
        b21.setIcon(new ImageIcon(myImage1));}
        out:{
        if(b21.getText().equals(b20.getText())&&b21.getText().equals(b22.getText()))
        {
            if(turn%2==0){
            JOptionPane.showMessageDialog(this,"Player1:"+player1+" Won", "Result", 1);
            p1score.setText(Integer.toString(++p1wins));}
            else{
            JOptionPane.showMessageDialog(this,"Player2:"+player2+" Won", "Result", 1);
             p2score.setText(Integer.toString(++p2wins));}
            pvc.setText(Integer.toString(++playc));
               dc=1;
            jButton2ActionPerformed(null);
            break out;
        }
                if(b21.getText().equals(b01.getText())&&b21.getText().equals(b11.getText())){
              if(turn%2==0){
            JOptionPane.showMessageDialog(this,"Player1:"+player1+" Won", "Result", 1);
              p1score.setText(Integer.toString(++p1wins));}
            else{
            JOptionPane.showMessageDialog(this,"Player2:"+player2+" Won", "Result", 1);
               p2score.setText(Integer.toString(++p2wins));}
              pvc.setText(Integer.toString(++playc));
                dc=1;
              jButton2ActionPerformed(null);
              break out;
                }
                 if(b00.getText()!=" "&&b01.getText()!=" "&&b02.getText()!=" "&&b10.getText()!=" "&&b11.getText()!=" "&&b12.getText()!=" "&&b20.getText()!=" "&&b21.getText()!=" "&&b22.getText()!=" "){
JOptionPane.showMessageDialog(this,"Game Draw.NObody win", "Result", 1);
jButton2ActionPerformed(null);
break out;
}    
        
        turn++;
        
        bc21=1;}}
    }//GEN-LAST:event_b21MouseClicked

    private void b22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b22MouseClicked
        // TODO add your handling code here:
          if(bc22==0){
                 if(enter==0)
               {
                    player1=JOptionPane.showInputDialog(this, "player1 name(0)", rootPaneCheckingEnabled);
        player2=JOptionPane.showInputDialog(this, "player2 name(1)", rootPaneCheckingEnabled);
        p1.setText(player1);
        p2.setText(player2); 
               enter++;
               }
        if(turn%2==0){
        b22.setText("0");
        b22.setIcon(new ImageIcon(myImage));
        }
        else{b22.setText("1");
        b22.setIcon(new ImageIcon(myImage1));}
        out:{
        if(b22.getText().equals(b11.getText())&&b22.getText().equals(b00.getText()))
        {
            if(turn%2==0){
            JOptionPane.showMessageDialog(this,"Player1:"+player1+" Won", "Result", 1);
            p1score.setText(Integer.toString(++p1wins));}
            else{
            JOptionPane.showMessageDialog(this,"Player2:"+player2+" Won", "Result", 1);
             p2score.setText(Integer.toString(++p2wins));}
            pvc.setText(Integer.toString(++playc));
                dc=1;
            jButton2ActionPerformed(null);
            break out;
        }
                if(b22.getText().equals(b02.getText())&&b22.getText().equals(b12.getText())){
                if(turn%2==0){
            JOptionPane.showMessageDialog(this,"Player1:"+player1+" Won", "Result", 1);
                p1score.setText(Integer.toString(++p1wins));}
            else{
            JOptionPane.showMessageDialog(this,"Player2:"+player2+" Won", "Result", 1);
                 p2score.setText(Integer.toString(++p2wins));}
                pvc.setText(Integer.toString(++playc));
               dc=1;
                jButton2ActionPerformed(null);
                break out;
                }
               if(b22.getText().equals(b20.getText())&&b22.getText().equals(b21.getText())){
              if(turn%2==0){
            JOptionPane.showMessageDialog(this,"Player1:"+player1+" Won", "Result", 1);
              p1score.setText(Integer.toString(++p1wins));}
            else{
            JOptionPane.showMessageDialog(this,"Player2:"+player2+" Won", "Result", 1);
               p2score.setText(Integer.toString(++p2wins));}
              pvc.setText(Integer.toString(++playc));
                dc=1;
              jButton2ActionPerformed(null);
              break out;
                }         
        if(b00.getText()!=" "&&b01.getText()!=" "&&b02.getText()!=" "&&b10.getText()!=" "&&b11.getText()!=" "&&b12.getText()!=" "&&b20.getText()!=" "&&b21.getText()!=" "&&b22.getText()!=" "){
JOptionPane.showMessageDialog(this,"Game Draw.NObody win", "Result", 1);
jButton2ActionPerformed(null);
break out;
}
        turn++;
        
        bc22=1;}}

    }//GEN-LAST:event_b22MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
     jButton1ActionPerformed(evt);
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    jButton1ActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
jButton2ActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        About a=new About();
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            String cn = UIManager.getSystemLookAndFeelClassName();
            UIManager.setLookAndFeel(cn); // Use the native L&F
        } catch (Exception cnf) {
        } 
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ticktoe().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b00;
    private javax.swing.JLabel b01;
    private javax.swing.JLabel b02;
    private javax.swing.JLabel b10;
    private javax.swing.JLabel b11;
    private javax.swing.JLabel b12;
    private javax.swing.JLabel b20;
    private javax.swing.JLabel b21;
    private javax.swing.JLabel b22;
    private javax.swing.JLabel dvc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p1score;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p2score;
    private javax.swing.JLabel pvc;
    // End of variables declaration//GEN-END:variables
}
